export const SELECTED_DATE = 'SELECTED_DATE';
export const CURRENT_DATE = 'CURRENT_DATE';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const REQUEST_NEW_PASSWORD = 'REQUEST_NEW_PASSWORD';
export const REQUEST_NEW_PASSWORD_SUCCESS = 'REQUEST_NEW_PASSWORD_SUCCESS';
export const REQUEST_NEW_PASSWORD_ERROR = 'REQUEST_NEW_PASSWORD_ERROR';


export const USER_PROFILE = 'USER_PROFILE';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const CREATE_BOOKING = 'CREATE_BOOKING';
export const CREATE_BOOKING_ERROR = 'CREATE_BOOKING_ERROR';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const FETCH_BOOKINGS = 'FETCH_BOOKINGS';
export const FETCH_BOOKINGS_ERROR = 'FETCH_BOOKINGS_ERROR';
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const FETCH_CALENDAR_BOOKINGS = 'FETCH_CALENDAR_BOOKINGS';
export const FETCH_CALENDAR_BOOKINGS_ERROR = 'FETCH_CALENDAR_BOOKINGS_ERROR';
export const FETCH_CALENDAR_BOOKINGS_SUCCESS = 'FETCH_CALENDAR_BOOKINGS_SUCCESS';
export const FETCH_USER_BOOKINGS = 'FETCH_USER_BOOKINGS';
export const FETCH_USER_BOOKINGS_ERROR = 'FETCH_USER_BOOKINGS_ERROR';
export const FETCH_USER_BOOKINGS_SUCCESS = 'FETCH_USER_BOOKINGS_SUCCESS';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const DELETE_BOOKING_ERROR = 'DELETE_BOOKING_ERROR';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const EDIT_BOOKING = 'EDIT_BOOKING';
export const EDIT_BOOKING_ERROR = 'EDIT_BOOKING_ERROR';
export const EDIT_BOOKING_SUCCESS = 'EDIT_BOOKING_SUCCESS';

export const FETCH_SERVICES = 'FETCH_SERVICES';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const FETCH_SERVICES_BY_RESIDENCE = 'FETCH_SERVICES_BY_RESIDENCE';
export const FETCH_SERVICES_BY_RESIDENCE_ERROR = 'FETCH_SERVICES_BY_RESIDENCE_ERROR';
export const FETCH_SERVICES_BY_RESIDENCE_SUCCESS = 'FETCH_SERVICES_BY_RESIDENCE_SUCCESS';

export const FETCH_RESIDENCES = 'FETCH_RESIDENCES';
export const FETCH_RESIDENCES_ERROR = 'FETCH_RESIDENCES_ERROR';
export const FETCH_RESIDENCES_SUCCESS = 'FETCH_RESIDENCES_SUCCESS';
export const SET_SELECTED_RESIDENCE = 'SET_SELECTED_RESIDENCE';

export const FETCH_APARTMENTS = 'FETCH_APARTMENTS';
export const FETCH_APARTMENTS_ERROR = 'FETCH_APARTMENTS_ERROR';
export const FETCH_APARTMENTS_SUCCESS = 'FETCH_APARTMENTS_SUCCESS';

export const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE';

export const NEW_MESSAGE = 'NEW_MESSAGE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const SET_LAYOUT = 'SET_LAYOUT';

export const CLIENT_ID = '303832931161-5v8mqd2di5ben74v8u4qqflks68pvpf6.apps.googleusercontent.com';
